title: Pavel Nazimok
description: Pavel Nazimok Personal Website
baseurl: ""

username: Pavel Nazimok
typing_text: QA Engineer | SDET

email: pavelnazimok@gmail.com
linkedin_username: pavel-nazimok
github_username: pavelicii
stackoverflow_userid: 8356662

show_aboutme_card: true
about_me_title: About Me
about_me_description: >
  QA Automation Engineer | SDET with 8+ years of experience in software testing.
  <br><br>
  My work has included API, Web, Mobile, Load, and Desktop testing. During this time I have been involved in different 
  stages of the testing process, from manual regression testing to implementing test automation infrastructure from scratch.
  <br><br>
  I have worked on tasks such as:
  <ul>
    <li>Creating and maintaining automated E2E tests</li>
    <li>Building test automation frameworks</li>
    <li>Integrating tests with CI/CD pipelines with shift-left testing in mind</li>
    <li>Integrating test management systems</li>
    <li>Running tests in cloud environments</li>
    <li>Calculating test coverage and visualizing test reports</li>
  </ul>
  
  In recent years, Java has been my primary language. I have also worked with Kotlin, TypeScript, Python, Groovy, Scala, 
  Bash, and C# when specific tasks required it. I enjoy learning new technologies and applying them where they are useful.
  <br><br>
  Feel free to check my GitHub profile for a several coding examples and and an open-source pet project.

show_skills_card: true
skills_title: Skills

show_timeline_card: true
timeline_title: Education & Experience
cv_download_link: https://drive.google.com/file/d/1G_2FObq-Wo_f67iCiSIiF7XwmUrAG3VY/view?usp=sharing

show_projects_card: true
show_projects: true
projects_title: Work Projects
show_os_projects: true
os_projects_title: Portfolio Projects

show_contact_card: true
contact_title: Contacts
contact_description: Feel free to contact me wherever is comfortable for you

repository: pavelicii/pavelicii.github.io
projects:
  sort_by: stars
  exclude:
    archived: true
    forks: true
    projects:
      - pavelicii

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
