title: Pavelicii
description: Pavel Nazimok Personal Website
baseurl: ""

username: Pavel Nazimok
typing_text: QA Engineer / SDET

email: pavelnazimok@gmail.com
telegram_username: pavelicii
linkedin_username: pavelicii
github_username: pavelicii
stackoverflow_userid: 8356662
twitter_username: pavelicii
instagram_username: pavelicii
facebook_username: pavelicii

show_aboutme_card: true
about_me_title: About Me
about_me_description: > 
  QA Automation Engineer with the commitment to deliver superior software by implementing effective quality control 
  procedures and continuous testing process in the development lifecycle.
  <br><br>
  Throughout the 5 years of experience in API, Web, Mobile, Load, and Desktop testing I've been doing a lot of 
  activities starting from manual regression checks and ending with the implementation of a test automation 
  infrastructure from scratch, combining E2E and load tests, CI/CD and TMS integration, cloud-based test execution, 
  test coverage calculation, and test reports visualization.
  <br><br>
  With Java being my main language, I also had multiple side-tasks which required the use of Python, Groovy, Kotlin, 
  Scala, Bash, and C#. It was always a new enjoyable experience for me hence I'm constantly willing to learn new 
  technologies and practices. 
  <br><br>
  I'm a regular visitor to the professional IT conferences since I intend to be on the same page with the current trends 
  in testing and development. I also try to give back what I can to the QA community. For example, I've developed and 
  opensourced <a class="highlight-link" href="https://github.com/pavelicii/allpairs4j" target="_blank" rel="noreferrer">
  AllPairs4J</a>  — a Java library for pairwise test data generation. You can find it on my <a class="highlight-link" 
  href="https://github.com/pavelicii" target="_blank" rel="noreferrer">GitHub profile</a>, along with other coding 
  examples.

show_skills_card: true
skills_title: Skills

show_timeline_card: true
timeline_title: Education & Experience
cv_download_link: https://drive.google.com/file/d/1G_2FObq-Wo_f67iCiSIiF7XwmUrAG3VY/view?usp=sharing

show_projects_card: true
show_projects: true
projects_title: Work Projects
show_os_projects: true
os_projects_title: Portfolio Projects

show_contact_card: true
contact_title: Contacts
contact_description: Feel free to contact me wherever is comfortable for you

repository: pavelicii/pavelicii.github.io
projects:
  sort_by: stars
  exclude:
    archived: true
    forks: true
    projects:
      - pavelicii

google-analytics:
  id: "G-J9PTNXNH26"

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
